### ISSUE TITLE
PhotoPSD Template

### ISSUE THREAD

**Issue by cristiandonaraDEV** [timiliris/New_Gui_ServerSelector_blue_gold#1]
**THIS IS NOT AN ISSUE**

I'm working on a 1° PSD template, you can contact me to talk about that if you want

Telegram : https://t.me/DonnyDevIT
Discord : DonnyDev#5075

**Comment by timiliris** [comment]
Hi thanks a lot ,
but i'allready work with a psd i've make.
You are free to share it with the communauty , in the discord or as an addon if u prefer :)
